#!/bin/bash

perf record -F 90 -g ./build/while -s ./examples/generated.while

perf script > out.perf

# Script requires FlameGraph
# To use, replace the relative path with the path to your FlameGraph directory
~/Downloads/FlameGraph/stackcollapse-perf.pl ./out.perf > folded.perf
~/Downloads/FlameGraph/flamegraph.pl folded.perf > flamegraph.svg


